### ISSUE TITLE
Package.loadSettings is deprecated.

### ISSUE THREAD

**Issue by j2deme** [EXSyst/php-twig#7] opened 2015-05-14 23:09 UTC
Store package settings files in the `settings/` directory instead of `scoped-properties/`
```
Package.loadSettings (/opt/atom/resources/app/src/package.js:550:9)
<unknown> (/opt/atom/resources/app/src/package.js:172:43)
```

**Comment by craveytrain** [comment] 2015-05-21 03:57
This is a dupe of #6.

**Comment by Ener-Getick** [comment] 2015-05-31 17:43
Resolved by https://github.com/EXSyst/php-twig/commit/890dac6c847982f868cd0c8621ab5e2ccf38c66c

**Closed by Ener-Getick** 2015-05-31 17:43 UTC
Labels: duplicate
